/**
 * export.js. Generate a self-contained Arduino sketch.
 *
 * Output is a complete .ino file using the Adafruit_NeoPixel library.
 * The generated sketch implements exactly the same chase-with-trail
 * animation you saw in the preview (animation.js).
 *
 * If you change the preview behavior, change this template too. The
 * docs are honest about that.
 */

export function generateArduinoCode(state) {
  const { leds, sequence, style, export: exp } = state;
  const ledCount = leds.length;
  const seqLen   = sequence.length;

  // Map sequence (LED ids) to strip indices. Placement order is the
  // strip's wiring index. led.id is just an internal identifier; the
  // strip index is the position in the leds array (after sorting by
  // placement order).
  const idToIndex = new Map();
  leds.forEach((led, i) => idToIndex.set(led.id, i));
  const seqIndices = sequence.map(id => idToIndex.get(id)).filter(i => i !== undefined);

  const colorMode = style.colorMode === "rainbow" ? "RAINBOW"
                  : style.colorMode === "perStep" ? "PER_STEP" : "SINGLE";
  const baseRGB = hexToRgbTuple(style.color);
  const perStepColors = (style.colorMode === "perStep")
    ? sequence.map((_, i) => style.perStepColors[i] || style.color).map(hexToRgbTuple)
    : null;

  // ---- Build the sketch ----
  const lines = [];
  lines.push("// ----------------------------------------------------------");
  lines.push("// NeoPixel Animation. Generated by NeoPixel Planner.");
  lines.push("// Plays a chase-with-trail along a user-defined sequence.");
  lines.push("// Adjust LED_PIN below to match your wiring.");
  lines.push("// Requires: Adafruit_NeoPixel library");
  lines.push("//   Arduino IDE > Sketch > Include Library > Manage Libraries");
  lines.push("//   Search 'Adafruit NeoPixel' > Install");
  lines.push("// ----------------------------------------------------------");
  lines.push("#include <Adafruit_NeoPixel.h>");
  lines.push("");
  lines.push(`#define LED_PIN     ${exp.pin}`);
  lines.push(`#define LED_COUNT   ${ledCount}`);
  lines.push(`#define BRIGHTNESS  ${style.brightness}    // 0..255`);
  lines.push(`#define INTERVAL_MS ${style.intervalMs}    // ms between sequence steps`);
  lines.push(`#define TRAIL_LEN   ${style.trail}     // 0 = single dot, N = N LEDs of fading tail`);
  lines.push("");
  lines.push(`Adafruit_NeoPixel strip(LED_COUNT, LED_PIN, ${exp.type});`);
  lines.push("");

  // Sequence array.
  if (seqLen === 0) {
    lines.push("// No sequence built yet. Fill from placement order at runtime.");
    lines.push("uint16_t sequence[LED_COUNT];");
    lines.push("const uint16_t SEQ_LEN = LED_COUNT;");
  } else {
    lines.push("// Animation order: indices into the LED strip, in the order they fire.");
    lines.push(`const uint16_t sequence[] = { ${seqIndices.join(", ")} };`);
    lines.push("const uint16_t SEQ_LEN = sizeof(sequence) / sizeof(sequence[0]);");
  }
  lines.push("");

  // Color mode.
  lines.push(`#define COLOR_MODE_${colorMode}`);
  if (colorMode === "SINGLE") {
    lines.push(`const uint8_t BASE_R = ${baseRGB.r};`);
    lines.push(`const uint8_t BASE_G = ${baseRGB.g};`);
    lines.push(`const uint8_t BASE_B = ${baseRGB.b};`);
  } else if (colorMode === "PER_STEP" && perStepColors) {
    lines.push("// Color per sequence step (R, G, B):");
    lines.push("const uint8_t stepColors[][3] = {");
    perStepColors.forEach(c => {
      lines.push(`  { ${c.r}, ${c.g}, ${c.b} },`);
    });
    lines.push("};");
  }
  // RAINBOW computes color at runtime, no constants needed.
  lines.push("");

  // setup()
  lines.push("uint16_t headStep = 0;");
  lines.push("unsigned long lastUpdate = 0;");
  lines.push("");
  lines.push("void setup() {");
  if (seqLen === 0) {
    lines.push("  for (uint16_t i = 0; i < LED_COUNT; i++) sequence[i] = i;");
  }
  lines.push("  strip.begin();");
  lines.push("  strip.setBrightness(BRIGHTNESS);");
  lines.push("  strip.show();");
  lines.push("}");
  lines.push("");

  // colorForStep helper.
  lines.push("// Returns the color for a given position in the sequence.");
  lines.push("uint32_t colorForStep(uint16_t seqPos) {");
  if (colorMode === "RAINBOW") {
    lines.push("  uint16_t hue = (uint16_t)((uint32_t)seqPos * 65535UL / SEQ_LEN);");
    lines.push("  return strip.gamma32(strip.ColorHSV(hue));");
  } else if (colorMode === "PER_STEP") {
    lines.push("  if (seqPos >= sizeof(stepColors)/sizeof(stepColors[0])) seqPos = 0;");
    lines.push("  return strip.Color(stepColors[seqPos][0], stepColors[seqPos][1], stepColors[seqPos][2]);");
  } else {
    lines.push("  return strip.Color(BASE_R, BASE_G, BASE_B);");
  }
  lines.push("}");
  lines.push("");

  // loop()
  lines.push("void loop() {");
  lines.push("  unsigned long now = millis();");
  lines.push("  if (now - lastUpdate < INTERVAL_MS) return;");
  lines.push("  lastUpdate = now;");
  lines.push("");
  lines.push("  strip.clear();");
  lines.push("");
  lines.push("  // Render head + trail. Trail fades by index.");
  lines.push("  for (int t = 0; t <= TRAIL_LEN && t < SEQ_LEN; t++) {");
  lines.push("    int seqPos = ((int)headStep - t + SEQ_LEN) % SEQ_LEN;");
  lines.push("    uint16_t ledIdx = sequence[seqPos];");
  lines.push("    uint32_t c = colorForStep(seqPos);");
  lines.push("    // Brightness factor: 255 at head, fades to ~0 at trail end.");
  lines.push("    uint16_t fade = 255 - ((uint32_t)t * 255 / (TRAIL_LEN + 1));");
  lines.push("    uint8_t r = ((c >> 16) & 0xFF) * fade / 255;");
  lines.push("    uint8_t g = ((c >>  8) & 0xFF) * fade / 255;");
  lines.push("    uint8_t b = ( c        & 0xFF) * fade / 255;");
  lines.push("    strip.setPixelColor(ledIdx, r, g, b);");
  lines.push("  }");
  lines.push("");
  lines.push("  strip.show();");
  lines.push("  headStep = (headStep + 1) % SEQ_LEN;");
  lines.push("}");
  lines.push("");
  lines.push("// ----------------------------------------------------------");
  lines.push("// Generated by NeoPixel Planner.");
  lines.push("// Want to change the animation? Edit it in the planner and");
  lines.push("// re-export, or tweak the constants above directly.");
  lines.push("// ----------------------------------------------------------");

  return lines.join("\n");
}

function hexToRgbTuple(hex) {
  const m = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex || "#691139");
  if (!m) return { r: 105, g: 17, b: 57 };
  return { r: parseInt(m[1], 16), g: parseInt(m[2], 16), b: parseInt(m[3], 16) };
}
